theme: jekyll-theme-cayman
title: Let's Learn! Spanish edition.
description: Simple steps to perfect Spanish.
github:
  LearningObjectives: LearningObjectives.html
  BasicNouns: BasicNouns.html
  page4: page4.html
  page5: page5.html
